### PR TITLE
Add crop event

### PR DESCRIPTION
**Pull request by sascha-frinken**
After a rotate the image did not show the modification.

Adding the crop event fixed the problem.

### CODE REVIEW

**Comment by F0rce** [comment]
Hi @sascha-frinken,

I saw your email this morning and will merge and update the cropper to your needs as soon as possible (probably by the end of today) :)

I will aditionally patch cropper.js to [v1.5.13](https://github.com/fengyuanchen/cropperjs/releases/tag/v1.5.13) and build/compile the project with the latest vaadin 14 version.

I'm stuck in other projects at the moment, so I haven't been able to work on my add-ons.

Sorry for the delayed reply,
David

**Comment by sascha-frinken** [comment]
👍🏿

**Comment by F0rce** [comment]
@sascha-frinken sorry for the delay, but the updated version has just been published to the Vaadin Directory

https://vaadin.com/directory/component/cropperjs/1.0.3

**Comment by sascha-frinken** [comment]
Thank you very much!

**Pull request merged**
